### ISSUE TITLE
ReferenceError: page is not defined

### ISSUE THREAD

**Issue by elebumm** [christopherwk210/site-scan#2]
Whenever I try and run I get this error

```
(node:5483) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: page is not defined
(node:5483) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by christopherwk210** [comment]
This should have been fixed with https://github.com/christopherwk210/site-scan/commit/f30c7b7e9698c4727e078f40309436b808d7b75e, you may have to reinstall. What version of site-scan is shown when you run `npm list -g`?

**Comment by dkatten** [comment]
I'm having the same issue
```
~/code/site-scan ∙ npm list -g | grep site  
└─┬ site-scan@1.0.3
```

I've also attempted a local build, with `node ./lib/site-scan.js google.com` and gotten the same issue. This is with node 7.x and 8.x.

**Comment by christopherwk210** [comment]
Thanks, part of the problem was that exceptions were not being properly thrown, which I've just fixed in https://github.com/christopherwk210/site-scan/commit/720c3a4cef4cd2bc970ea11df363619fbbae7bf2. Please update the package and report the output :)

**Comment by dkatten** [comment]
Fraid it's the same:
```
~/code/site-scan ∙ npm i -g site-scan                     
/Users/davekatten/.nvm/versions/node/v8.6.0/bin/sitescan -> /Users/davekatten/.nvm/versions/node/v8.6.0/lib/node_modules/site-scan/lib/site-scan.js
/Users/davekatten/.nvm/versions/node/v8.6.0/bin/ss -> /Users/davekatten/.nvm/versions/node/v8.6.0/lib/node_modules/site-scan/lib/site-scan.js
+ site-scan@1.0.4
updated 1 package in 8.021s
~/code/site-scan ∙ ss google.com                   
• Launching chrome...
✔ Done.

(node:19105) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: page is not defined
(node:19105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also, I have chromedriver 2.33 installed via homebrew.

**Comment by christopherwk210** [comment]
Thanks for following up! I didn't have chromedriver on my system so I went ahead and installed it with homebrew. After that I started to get the same error you did. I was able to fix the issue for me in https://github.com/christopherwk210/site-scan/commit/20d87acf8c4e5316550f0fd9428a051cfc45270e, please update one more time and let me know if it works 👍

**Comment by dkatten** [comment]
success! thanks. A local build with node 8.6 worked for me.
